TaskWise/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', include('tasks.urls')),  # Note this change here; it includes 'tasks.urls' at the root.
]

tasks/urls.py
from django.urls import path
from . import views
from .views import CreateProductView, ProductListView, TaskListView, SaleListView, change_password, edit_contact, create_company, create_individual, index, create_task, product_delete, settings_contact_list, task_detail, delete_task, sale_detail, create_sale, edit_sale, delete_sale, contact_list, contact_detail, settings_view, update_user_info

urlpatterns = [
    # Homepage URL
    path('', index, name='home'),
    
    # Dashboard URL, displaying an overview of the application
    path('dashboard/', views.dashboard, name='dashboard'),
    
    # Task-related URLs for listing, detail view, creation, and deletion
    path('tasks/', TaskListView.as_view(), name='task_list'),
    path('tasks/<int:task_id>/', task_detail, name='task_detail'),
    path('tasks/create_task/', create_task, name='create_task'),
    path('ajax/load-subcategories/', views.ajax_load_subcategories, name='ajax_load_subcategories'),
    path('tasks/edit_task/<int:task_id>/', views.edit_task, name='edit_task'),
    path('tasks/delete_task', delete_task, name='delete_task'),
    path('tasks/assign_to_me/<int:task_id>/', views.assign_to_me, name='assign_to_me'),

    # Sale-related URLs for listing, detail view, creation, and editing
    path('sales/', SaleListView.as_view(), name='sale_list'),
    path('sales/<int:sale_id>/', sale_detail, name='sale_detail'),
    path('sales/create_sale/<int:task_id>/', create_sale, name='create_sale'),
    path('sales/edit_sale/<int:sale_id>/', views.edit_sale, name='edit_sale'),
    path('sales/delete/', delete_sale, name='delete_sale'),
    
    # Contact-related URLs for listing and detailed views
    path('contacts/', contact_list, name='contact_list'),
    path('individuals/<int:id>/', edit_contact, {'contact_type': 'individual'}, name='edit_individual'),
    path('companies/<int:id>/', edit_contact, {'contact_type': 'company'}, name='edit_company'),
    path('contacts/individuals/contact_detail/<int:id>/', contact_detail, {'contact_type': 'individual'}, name='individual_contact_detail'),
    path('contacts/companies/contact_detail/<int:id>/', contact_detail, {'contact_type': 'company'}, name='company_contact_detail'),
    path('contacts/company/create/', create_company, name='create_company'),
    path('contacts/individual/create/', create_individual, name='create_individual'),
    path('update_contact_info/<int:contact_id>/<contact_type>/', views.update_contact_info, name='update_contact_info'),
    path('contact/delete/<int:contact_id>/<str:contact_type>/', views.contact_delete, name='contact_delete'),

    # Product-related URLs for listing, detail view, and settings
    path('products/', ProductListView.as_view(), name='product_list'),
    path('products/<int:id>/', views.product_detail, name='product_detail'),

    # Settings and user information update URLs
    path('settings/', settings_view, name='settings'),
    path('update_user_info/', update_user_info, name='update_user_info'),
    path('settings/password/', change_password, name='change_password'),
    path('settings/products/', ProductListView.as_view(), name='product_list_settings'),
    path('settings/products/<int:id>/', views.product_detail, name='product_detail_settings'),
    path('settings/edit_products/<int:id>/', views.product_settings, name='product_settings'),
    path('settings/delete_product/', product_delete, name='product_delete'),  
    path('settings/product/create/', CreateProductView.as_view(), name='create_product'),
    
]

tasks/models.py
from django.db import models
from django.forms import ValidationError
from django.utils import timezone
from django.contrib.auth.models import User
from django.conf import settings

# Provides predefined choices for the status of tasks and sales.
class StatusChoices(models.TextChoices):
    NEW = 'New', 'New'
    IN_PROGRESS = 'In Progress', 'In Progress'
    PENDING_CUSTOMER = 'Pending Customer', 'Pending Customer'
    PENDING_PARTNER = 'Pending Partner', 'Pending Partner'
    ESCALATED = 'Escalated', 'Escalated'
    COMPLETED = 'Completed', 'Completed'

# Defines priority levels for tasks to help with sorting and management.
class PriorityChoices(models.TextChoices):
    HIGH_PRIORITY = 'High Priority', 'High Priority'
    MEDIUM_HIGH_PRIORITY = 'Medium-High Priority', 'Medium-High Priority'
    MEDIUM_LOW_PRIORITY = 'Medium-Low Priority', 'Medium-Low Priority'
    LOW_PRIORITY = 'Low Priority', 'Low Priority'

# Represents an individual, potentially a contact for a company.
class Individual(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=15, blank=True)
    address = models.TextField(blank=True)
    company = models.ForeignKey('Company', related_name='individuals', on_delete=models.SET_NULL, null=True, blank=True)
    additional_details = models.TextField(blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    last_updated_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='individual_updates', on_delete=models.SET_NULL, null=True, blank=True)


    def __str__(self):
        return self.name

# Represents a company, which may be associated with various individuals.
class Company(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=15, blank=True)
    address = models.TextField(blank=True)
    additional_details = models.TextField(blank=True)
    registration_number = models.CharField(max_length=100, unique=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    reference = models.ForeignKey(Individual, related_name='company_references', on_delete=models.SET_NULL, null=True, blank=True)
    owner = models.ForeignKey(Individual, related_name='company_owners', on_delete=models.SET_NULL, null=True, blank=True)
    last_updated_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='company_updates', on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.name

    def clean(self):
        # Validates that reference and owner are not associated with a different company.
        if self.reference and self.reference.company and self.reference.company != self:
            raise ValidationError("Reference must not be associated with a different company")
        if self.owner and self.owner.company and self.owner.company != self:
            raise ValidationError("Owner must not be associated with a different company")

    def save(self, *args, **kwargs):
        self.clean()  # Calls clean method to perform custom validation before saving.
        super().save(*args, **kwargs)

# Represents a product that can be sold.
class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    serial_number = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

# Represents a sale transaction.
class Sale(models.Model):
    task = models.ForeignKey('Task', related_name='sales', on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=50, choices=StatusChoices.choices, default=StatusChoices.NEW)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    last_updated_by = models.ForeignKey(User, related_name='sale_updates', on_delete=models.SET_NULL, null=True, blank=True)
    products = models.ManyToManyField(Product, through='SaleProduct', related_name='sales')

    def __str__(self):
        return f"Sale {self.id}"

# Intermediate model for Sale and Product to include quantity.
class SaleProduct(models.Model):
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.sale} - {self.product} (Quantity: {self.quantity})"
    
# Represents a general category for grouping tasks.
class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

# Represents a more specific grouping within a Category for tasks.
class SubCategory(models.Model):
    category = models.ForeignKey(Category, related_name='subcategories', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)

    def __str__(self):
        return f"{self.category.name} - {self.name}"
    
# Represents a task or job to be done, associated with various details like status and priority.
class Task(models.Model):
    user = models.ForeignKey(User, related_name='tasks', on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()
    contact = models.ForeignKey(Individual, related_name='tasks', on_delete=models.SET_NULL, null=True, blank=True)
    category = models.ForeignKey(Category, related_name='tasks', on_delete=models.SET_NULL, null=True)
    subcategory = models.ForeignKey(SubCategory, related_name='tasks', on_delete=models.SET_NULL, null=True)
    status = models.CharField(max_length=50, choices=StatusChoices.choices, default=StatusChoices.NEW)
    priority = models.CharField(max_length=20, choices=PriorityChoices.choices, default=PriorityChoices.LOW_PRIORITY)
    regarding = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True, related_name='related_tasks')
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    last_updated_by = models.ForeignKey(User, related_name='task_updates', on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.title

tasks/forms.py
from django import forms
from .models import Company, Individual, Product, Task, Category, SubCategory, Sale
import uuid

# TaskForm: Handles the form logic for creating and updating Task instances.
class TaskForm(forms.ModelForm):
    title = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Task
        fields = ['user', 'title', 'description', 'contact', 'category', 'subcategory', 'status', 'regarding', 'priority']
        widgets = {
            # You can specify any custom widgets here.
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(TaskForm, self).__init__(*args, **kwargs)

        # Ensure unique title for new tasks
        if not self.instance.pk:
            unique_id = uuid.uuid4().hex[:4].upper()
            second_unique_id = uuid.uuid4().hex[:4].upper()
            self.fields['title'].initial = f"TASK-{unique_id}-{second_unique_id}"

        # Set querysets for category and subcategory
        self.fields['category'].queryset = Category.objects.all()
        self.fields['subcategory'].queryset = SubCategory.objects.none()

        # Apply Bootstrap classes for styling
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name in ['category', 'subcategory', 'contact', 'regarding', 'priority']:
                field.widget.attrs['class'] += ' form-select'

        # Set initial values for certain fields
        if user:
            self.fields['user'].initial = user
        self.fields['status'].initial = 'New'
        self.fields['priority'].initial = 'Low Priority'

        # Update subcategory queryset based on category selection
        if 'category' in self.data:
            try:
                category_id = int(self.data.get('category'))
                self.fields['subcategory'].queryset = SubCategory.objects.filter(category_id=category_id).order_by('name')
            except (ValueError, TypeError):
                pass  # An empty queryset will be used if the category ID is invalid
        elif self.instance.pk:
            self.fields['subcategory'].queryset = self.instance.category.subcategories.order_by('name')

        # Update regarding queryset to exclude current instance
        if self.instance.pk:
            self.fields['regarding'].queryset = Task.objects.exclude(pk=self.instance.pk)
        else:
            self.fields['regarding'].queryset = Task.objects.all()

    def save(self, commit=True):
        instance = super(TaskForm, self).save(commit=False)
        
        # Link task to a company based on the contact's company, if available
        if instance.contact:
            instance.company = instance.contact.company
        
        # Prevent title change for existing tasks
        if self.instance.pk:
            original_instance = Task.objects.get(pk=self.instance.pk)
            instance.title = original_instance.title
        
        if commit:
            instance.save()
            self._save_m2m()

        return instance

# SaleForm: Manages Sale instance forms.
class SaleForm(forms.ModelForm):
    class Meta:
        model = Sale
        fields = ['status']

    def __init__(self, *args, **kwargs):
        super(SaleForm, self).__init__(*args, **kwargs)
        # Applies Bootstrap classes for styling.
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control form-select'

# ProductForm: Handles forms for Product instances.
class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'serial_number']

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        # Applies Bootstrap classes for styling.
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if isinstance(field, (forms.fields.ChoiceField, forms.ModelChoiceField)):
                field.widget.attrs['class'] += ' form-select'

# CompanyForm: Manages forms for Company instances.
class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ['name', 'email', 'phone', 'address', 'additional_details', 'registration_number']
        widgets = {
            'address': forms.TextInput(attrs={'class': 'form-control'}),  # Changed to TextInput
            'additional_details': forms.TextInput(attrs={'class': 'form-control'}),  # Changed to TextInput
        }

    def __init__(self, *args, **kwargs):
        super(CompanyForm, self).__init__(*args, **kwargs)
        # Applies Bootstrap classes for styling.
        for field_name, field in self.fields.items():
            if field_name not in ['address', 'additional_details']:  # These already have custom widgets
                field.widget.attrs['class'] = 'form-control'
            if isinstance(field, (forms.fields.ChoiceField, forms.ModelChoiceField)):
                field.widget.attrs['class'] += ' form-select'

# IndividualForm: Manages forms for Individual instances.
class IndividualForm(forms.ModelForm):
    class Meta:
        model = Individual
        fields = ['name', 'email', 'phone', 'address', 'company', 'additional_details']
        widgets = {
            'address': forms.TextInput(attrs={'class': 'form-control'}),  # Already set to TextInput
            'additional_details': forms.TextInput(attrs={'class': 'form-control'}),  # Add this line
        }

    def __init__(self, *args, **kwargs):
        super(IndividualForm, self).__init__(*args, **kwargs)
        # Applies Bootstrap classes for styling.
        for field_name, field in self.fields.items():
            if field_name not in ['address', 'additional_details']:  # These already have custom widgets
                field.widget.attrs['class'] = 'form-control'
            if isinstance(field, forms.ModelChoiceField):
                field.widget.attrs['class'] += ' form-select'

tasks/templates/tasks/create_task.html
{% extends 'global/base.html' %}

{% block title %}Tasks{% endblock %}

{% block sidebar %}
    {% include 'global/sidebar.html' %}
{% endblock %}

{% block content %}

{% include 'global/top_menu.html' %}

<!-- Content -->
<div class="container mt-5">
    <h4>Create a New Task</h4>
    <form id="taskForm" method="post" data-subcategories-url="{% url 'ajax_load_subcategories' %}">
        {% csrf_token %}
        {{ form.user.as_hidden }}
        {{ form.status.as_hidden }}
        {{ form.title.as_hidden }}  <!-- Render the title as a hidden field -->
        <div class="mb-3">
            <label for="taskTitle">Task Title</label>
            <!-- Display the generated title for new tasks or the existing title for existing tasks -->
            <input type="text" id="taskTitle" value="{{ form.title.value }}" class="form-control" disabled>
        </div>
        <!-- Render the rest of the form fields here, excluding the title field -->
        {% for field in form %}
            {% if field.name not in exclude_fields and field.name != 'title' %}
                <div class="mb-3">
                    {{ field.label_tag }}
                    {{ field }}
                </div>
            {% endif %}
        {% endfor %}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

{% block scripts %}
{{ block.super }}
<script type="text/javascript">
    $(document).ready(function() {
        $('#id_category').select2({ placeholder: 'Select Category' });
        $('#id_subcategory').select2({ placeholder: 'Select Subcategory' });
        $('#id_individual').select2({ placeholder: 'Select Individual' });
        $('#id_regarding').select2({ placeholder: 'Select Regarding' });
        $('#id_category').on('change', function() {
            var url = $("#taskForm").attr("data-subcategories-url");
            var categoryId = $(this).val();

            $.ajax({
                url: url,
                data: {
                    'category': categoryId
                },
                success: function (data) {
                    $("#id_subcategory").html(data.html);
                    $('#id_subcategory').select2({ placeholder: 'Select Subcategory' });
                }
            });
        });
    });
</script>
{% endblock %}

tasks/templates/tasks/edit_task.html
{% extends 'global/base.html' %}

{% block title %}Edit Task{% endblock %}

{% block sidebar %}
    {% include 'global/sidebar.html' %}
{% endblock %}

{% block content %}
<!-- Top menu -->
<div class="container-fluid mt-4">
    <nav class="navbar navbar-expand-lg navbar-light rounded">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavCompact" aria-controls="navbarNavCompact" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavCompact">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" href="#" onclick="history.back();"><i class="bi bi-caret-left"></i> Back</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>

<!-- Content -->
<div class="container mt-5">
    <div class="card light-shadow">
        <div class="card-header card-title">
            <strong>Edit Task: {{ form.instance.title }}</strong>
        </div>
        <div class="card-body">
            <form id="taskForm" method="post" action="" class="row">
                {% csrf_token %}
                {{ form.user.as_hidden }}
                <!-- Left Column for Description -->
                <div class="col-md-6">
                    <ul class="list-group list-group-flush">
                        {% for field in form %}
                            {% if field.name == "description" %}
                                <li class="list-group-item">
                                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                                    {{ field }}
                                    {% if field.help_text %}
                                        <small class="form-text text-muted">{{ field.help_text }}</small>
                                    {% endif %}
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
                <!-- Right Column for Other Fields -->
                <div class="col-md-6">
                    <ul class="list-group list-group-flush">
                        <!-- Status Field -->
                        <li class="list-group-item">
                            <label for="{{ form.status.id_for_label }}" class="form-label">{{ form.status.label }}</label>
                            {{ form.status }}
                            {% if form.status.help_text %}
                                <small class="form-text text-muted">{{ form.status.help_text }}</small>
                            {% endif %}
                        </li>
                        <!-- Other Fields -->
                        {% for field in form %}
                            {% if field.name != "description" and field.name != "status" and field.name not in exclude_fields %}
                                <li class="list-group-item">
                                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                                    {{ field }}
                                    {% if field.help_text %}
                                        <small class="form-text text-muted">{{ field.help_text }}</small>
                                    {% endif %}
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
                <!-- Submit Button -->
                <div class="col-md-12 text-center mt-3">
                    <button type="submit" class="btn btn-primary">Save Changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

{% block scripts %}
{{ block.super }}
<script type="text/javascript">
    $(document).ready(function() {
        $('#id_category').select2({ placeholder: 'Select Category' });
        $('#id_subcategory').select2({ placeholder: 'Select Subcategory' });
        $('#id_individual').select2({ placeholder: 'Select Individual' });
        $('#id_regarding').select2({ placeholder: 'Select Regarding' });
        $('#id_category').on('change', function() {
            var url = $("#taskForm").attr("data-subcategories-url");
            var categoryId = $(this).val();

            $.ajax({
                url: url,
                data: {
                    'category': categoryId
                },
                success: function (data) {
                    $("#id_subcategory").html(data.html);
                    $('#id_subcategory').select2({ placeholder: 'Select Subcategory' });
                }
            });
        });
    });
</script>
{% endblock %}

tasks/templates/tasks/subcategory_dropdown_list_options.html
<option value="">---------</option>
{% for subcategory in subcategories %}
<option value="{{ subcategory.pk }}">{{ subcategory.name }}</option>
{% endfor %}

tasks/templates/tasks/task_list.html
{% extends 'global/base.html' %}

{% block title %}
Task List
{% endblock %}

{% block sidebar %}
{% include 'global/sidebar.html' %}
{% endblock %}

{% block content %}
<form method="post" action="{% url 'delete_task' %}">
    {% csrf_token %}
<!-- Top menu -->
<div class="container-fluid mt-4">
    <nav class="navbar navbar-expand-lg navbar-light rounded">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link active" href="#" onclick="history.back();"><i class="bi bi-caret-left"></i> Back</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'task_list' %}?list=all"><i class="bi bi-check-all"></i> All Tasks</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'task_list' %}?list=my_tasks"><i class="bi bi-tags"></i> My Tasks</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'task_list' %}?list=my_team"><i class="bi bi-people"></i> My Team's Tasks</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'create_task' %}"><i class="bi bi-plus-circle"></i> Create Task</a>
            </li>
            <li class="nav-item">
                    <button type="submit" class="btn btn-danger btn-sm">Delete Tasks</button>
            </li>
          </ul>
          <div>
            <input class="form-control me-2" type="search" placeholder="Search tasks" aria-label="Search" id="taskSearch">
          </div>   
        </div>
      </div>
    </nav>
</div>
<!-- Messages -->
<div class="container-fluid mt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show small-alert" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
    {% endif %}
</div>
<!-- Page title -->
<div class="mt-3 mb-3">
    <h4>{{ page_title }}</h4>
</div>

<!-- Tasks table -->
<div class="table-responsive scrollable-table">
    <table class="table table-hover" id="taskTable">
        <thead class="table-light">
            <tr>
                <th>Select</th>
                <th>Title</th>
                <th>Description</th>
                <th>Status</th>
                <th>Assigned to</th>
                <th>Category</th>
                <th>Subcategory</th>
                <th>Company</th>
                <th>Individual</th>
                <th>Created At</th>
                <th>Last Updated</th>
            </tr>
        </thead>
        <tbody>
            {% for task in tasks %}
            <tr>
                <td><input type="checkbox" name="task_ids" value="{{ task.id }}"></td>
                <td><a href="{% url 'task_detail' task_id=task.id %}">{{ task.title }}</a></td>
                <td>{{ task.description|truncatechars:100 }}</td>
                <td>{{ task.get_status_display }}</td>
                <td>{{ task.user.username }}</td>
                <td>{% if task.category %}{{ task.category.name }}{% else %}N/A{% endif %}</td>
                <td>{% if task.subcategory %}{{ task.subcategory.name }}{% else %}N/A{% endif %}</td>
                <td>{% if task.contact.company.name %}{{ task.contact.company.name }}{% else %}N/A{% endif %}</td>
                <td>{% if task.contact.name %}{{ task.contact.name }}{% else %}N/A{% endif %}</td>
                <td>{{ task.created_at|date:"Y-m-d H:i" }}</td>
                <td>{{ task.updated_at|date:"Y-m-d H:i" }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="11">No tasks found.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
</form>
{% endblock %}
{% block scripts %}
{{ block.super }}
<script>
    function confirmDelete() {
        return confirm('Are you sure you want to delete the selected tasks?');
    }

    $(document).ready(function() {
        $('#taskSearch').on('keyup', function() {
            var searchTerm = $(this).val();
            $.ajax({
                url: "{% url 'task_list' %}",
                data: { 'search': searchTerm },
                success: function(response) {
                    var html = '';
                    if (response.data.length === 0) {
                        html = '<tr><td colspan="11">No tasks found.</td></tr>';
                    } else {
                        response.data.forEach(function(task) {
                            html += '<tr>' +
                                    `<td><input type="checkbox" name="task_ids" value="${task.id}"></td>` +
                                    `<td><a href="{% url 'task_detail' task_id=0 %}`.replace('0', task.id) + `">${task.title}</a></td>` +
                                    `<td>${task.description}</td>` +
                                    `<td>${task.status}</td>` +
                                    `<td>${task.user__username}</td>` +
                                    `<td>${task.category__name || 'N/A'}</td>` +
                                    `<td>${task.subcategory__name || 'N/A'}</td>` +
                                    `<td>${task.company__name || 'N/A'}</td>` +
                                    `<td>${task.contact__name || 'N/A'}</td>` +
                                    `<td>${new Date(task.created_at).toLocaleString()}</td>` +
                                    `<td>${new Date(task.updated_at).toLocaleString()}</td>` +
                                    '</tr>';
                        });
                    }
                    $('#taskTable tbody').html(html);
                },
                error: function(xhr, status, error) {
                    console.error("AJAX error:", status, error);
                }
            });
        });

        // Attach the confirmDelete function to the form submit event
        $('form').submit(function() {
            return confirmDelete();
        });
    });
</script>
{% endblock %}